language: ruby
rvm:
- 2.2.0

addons:
  postgresql: '9.3'

before_script:
- cp config/database.yml.sample config/database.yml
- psql -c 'create database linkguru_test;' -U linkguru

deploy:
  provider: heroku
  api_key:
    secure: AaCDEfp2GVusMS72rHFK8O7Zu7NjAB+G/p8rES/qwHzB68pk+DvalBSJQGwLT/+nsqKpG/2iIlGlS3cEX7aYK6Gvkp7YS9DzKvjgySmpA+6D9zt0N/l/nNFrYZRPAcF8mREY/rZRmdtGRaO/8mDVoYrs/rX/FsAEPSnJNL/zHLE=
  app: linkguru
